<?php


if ( !function_exists( 'shoestrap_phpsass_compiler' ) ) :
/*
 * This function can be used to compile an scss file to css using the scssphp compiler
 */
function shoestrap_phpsass_compiler() {

  $formatter = ( shoestrap_getVariable( 'minimize_css', true ) == 1 ) ?
    'scss_formatter_compressed' :
    'scss_formatter_nested';

  $scss = new scssc();
  $scss->setFormatter( $formatter );

  $css = $scss->compile( shoestrap_complete() );

  return apply_filters( 'shoestrap_compiler_output', $css );
}
endif;


if ( !function_exists( 'shoestrap_compile_css' ) ) :
function shoestrap_compile_css() {
  global $wp_filesystem;
  
  // Initialize the Wordpress filesystem, no more using file_put_contents function
  if ( empty( $wp_filesystem ) ) :
    require_once( ABSPATH . '/wp-admin/includes/file.php' );
    WP_Filesystem();
  endif;
  $content = '/********* Do not edit this file *********/

';
  
  $content .= shoestrap_phpsass_compiler();
  $file = shoestrap_css();

  if ( is_writeable( $file ) || ( !file_exists( $file ) && is_writeable( dirname( $file ) ) ) ) :
    if ( !$wp_filesystem->put_contents( $file, $content, FS_CHMOD_FILE ) ) :
      return $content;
    endif;
  endif;
}
endif;


if ( !function_exists( 'shoestrap_makecss' ) ) :
/*
 * Write the CSS to file
 */
function shoestrap_makecss() {
  shoestrap_compile_css();
}
endif;


if ( is_writable( get_template_directory() . '/assets/sass/custom.scss' ) ) :
  // If the Custom SCSS file has changed, trigger the compiler.
  if ( filemtime( get_template_directory() . '/assets/sass/custom.scss' ) != get_option( 'shoestrap_custom_scssfile_datetime' ) ) :
    shoestrap_makecss();
  endif;

  // Update the 'shoestrap_custom_scssfile_datetime' option with the new filem data of the custom.scss file
  update_option( 'shoestrap_custom_scssfile_datetime', filemtime( get_template_directory() . '/assets/scss/custom.scss' ) );
endif;