<?php


if ( !function_exists( 'shoestrap_phpsass_compiler' ) ) :
/*
 * This function can be used to compile a sass file to css using the sassphp compiler
 */
function shoestrap_phpsass_compiler( $sass = '', $syntax = 'scss', $style = '' ) {

  // Get the style to be used.
  if ( !$style ) :
    $style = ( shoestrap_getVariable( 'minimize_css', true ) == 1 ) ? 'compressed' : 'nested';
  endif;

  // What do you want to compile?
  $sass = ( !$sass ) ? shoestrap_complete_sass() : $sass;

  // Compiler options
  $options = array(
    'style'     => $style,
    'cache'     => FALSE,
    'syntax'    => $syntax,
    'debug'     => FALSE,
    'callbacks' => array(
      'warn'    => 'shoestrap_compiler_warn',
      'debug'   => 'shoestrap_compiler_debug',
    ),
  );

  // Execute the compiler.
  $parser = new SassParser( $options );
  $css = $parser->toCss( $sass );

  return apply_filters( 'shoestrap_compiler_output', $css );
}
endif;


function shoestrap_compiler_warn( $message, $context ) {
  print "<p class='alert alert-danger'>WARN : ";
  print_r($message);
  print "</p>";
}
function shoestrap_compiler_debug( $message ) {
  print "<p class='alert alert-warning'>DEBUG : ";
  print_r($message);
  print "</p>";
}

if ( !function_exists( 'shoestrap_compile_css' ) ) :
function shoestrap_compile_css() {
  global $wp_filesystem;
  
  // Initialize the Wordpress filesystem, no more using file_put_contents function
  if ( empty( $wp_filesystem ) ) :
    require_once( ABSPATH . '/wp-admin/includes/file.php' );
    WP_Filesystem();
  endif;
  $content = '/********* Do not edit this file *********/

';
  
  $content .= shoestrap_phpsass_compiler();
  $file = shoestrap_css();

  if ( is_writeable( $file ) || ( !file_exists( $file ) && is_writeable( dirname( $file ) ) ) ) :
    if ( !$wp_filesystem->put_contents( $file, $content, FS_CHMOD_FILE ) ) :
      return $content;
    endif;
  endif;
}
endif;


if ( !function_exists( 'shoestrap_makecss' ) ) :
/*
 * Write the CSS to file
 */
function shoestrap_makecss() {
  shoestrap_compile_css();
}
endif;


if ( is_writable( get_template_directory() . '/assets/sass/custom.scss' ) ) :
  // If the Custom SCSS file has changed, trigger the compiler.
  if ( filemtime( get_template_directory() . '/assets/sass/custom.scss' ) != get_option( 'shoestrap_custom_scssfile_datetime' ) ) :
    shoestrap_makecss();
  endif;

  // Update the 'shoestrap_custom_scssfile_datetime' option with the new filem data of the custom.scss file
  update_option( 'shoestrap_custom_scssfile_datetime', filemtime( get_template_directory() . '/assets/scss/custom.scss' ) );
endif;